config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :companies

  resources :entities
  resources :cities
  resources :streets

  get 'cat/:cid' => 'companies#list', as: 'companies_list'
  get ':city/:letter' => 'streets#list', as: 'streets_list', :defaults => { :letter => "A" }
  get 'streetsfix' => 'streets#fix'
  get 'page/index' => 'pages#index'
  get 'signin' => 'pages#signin', as: 'signin'

  get 'my' => 'companies#my', as: 'my'

  get 'page/welcome' => 'pages#welcome'

end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  load_and_authorize_resource
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params.require(:entity).permit(:name, :description, :phone, :address, :url)
    end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing Entity</h1>

<%= render 'form' %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

app/views/entities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= entity.name %></td>
        <td><%= entity.description %></td>
        <td><%= entity.phone %></td>
        <td><%= entity.address %></td>
        <td><%= entity.url %></td>
        <td><%= link_to 'Show', entity %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity) %></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

app/views/entities/new.html.erb
<h1>New Entity</h1>

<%= render 'form' %>

<%= link_to 'Back', entities_path %>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @entity.description %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @entity.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @entity.address %>
</p>

<p>
  <strong>Url:</strong>
  <%= @entity.url %>
</p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>