config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :companies

  resources :entities
  resources :cities
  resources :streets

  get 'cat/:cid' => 'companies#list', as: 'companies_list'
  get ':city/:letter' => 'streets#list', as: 'streets_list', :defaults => { :letter => "A" }
  get 'streetsfix' => 'streets#fix'
  get 'page/index' => 'pages#index'
  get 'signin' => 'pages#signin', as: 'signin'

  get 'my' => 'companies#my', as: 'my'

  get 'page/welcome' => 'pages#welcome'

end

app/models/company.rb
class Company < ActiveRecord::Base

	belongs_to :city
	belongs_to :category
	belongs_to :street
	belongs_to	:user
	acts_as_mappable :default_units => :kms,
                   	 :lat_column_name => :lat,
                   	 :lng_column_name => :lng
	scope :approved, -> {where(:hidden => false)}

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource :except => [:list, :show]
  before_filter :authorize_admin, only: :destroy
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :set_loc, only: [:create, :update]

  # GET /companies
  # GET /companies.json
  def index
    #@companies = Company.all
    redirect_to my_path
  end

  def my
    if(current_user.admin?)
      @companies = Company.all.order(created_at: :desc)
    else
    @companies = Company.where(user_id: current_user).order(created_at: :desc)
    end
  @markers ||=[]
  @companies.each do |company|
    puts company.lat
    linker = ActionController::Base.helpers.link_to(company.name, company_path(company.id))
    @markers << {:latlng => [company.lat, company.lng], :popup => linker + '\n' + company.street.name}

    end
  end


  def list
    @category = Category.find(params[:cid])
    @companies = Company.approved.where(category_id: params[:cid]).order(created_at: :desc)
    @markers ||=[]
    @companies.each do |company|
      puts company.lat
      linker = ActionController::Base.helpers.link_to(company.name, company_path(company.id))
      @markers << {:latlng => [company.lat, company.lng], :popup => linker + '\n' + company.street.name}

    end

  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    if @company.hidden? and !current_user.admin?
      redirect_to root_path, notice: 'Такой компании не существует'
    end
    #@location = Geokit::Geocoders::MultiGeocoder.geocode @city.name+@street.name+@company.hnum.to_s
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    @company.lat = @location.lat
    @company.lng = @location.lng
    @company.hidden = true
    @company.user = current_user
    respond_to do |format|
      if @company.save
        format.html { redirect_to my_path, notice: 'Организация успешно добавлена!' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update

    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to my_path, notice: 'Данные организации успешно обновлены.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to my_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    def set_loc
      @city = City.find(params[:company][:city_id])
      @street = Street.find(params[:company][:street_id])
      @address = @city.name+', '+@street.name+', '+params[:company][:hnum].to_s
      puts "****************************************"
      puts @address
      @location = Geokit::Geocoders::MultiGeocoder.geocode @address
      @company.lat = @location.lat
      @company.lng = @location.lng
      @company.address = @address
      puts @company.to_yaml
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.fetch(:company, {}).permit(:name, :hidden, :street_id, :hnum, :city_id, :category_id, :description, :phone, :website, :worktime)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper

	
end

app/views/companies/_company.html.erb
<div class="card">
  <div class="card-divider">
    <span class="title"><%= link_to company.name, company%></span>
    <% if !current_user.nil? && current_user.admin? %>

      <%= link_to 'Редактировать', edit_company_path(company), :class=>'button warning small' %>
      <%= link_to 'Удалить', company, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'button alert small' %>
    <% end %>
  </div>
  <div class="content">
      Категория: <%= link_to company.category.name, companies_list_path(company.category.id)%>
  </div>
  <div class="action">
      <%= link_to company.city.name, streets_list_path(city: company.city.name) %>, <%= link_to company.street.name, company.street %>, <%= company.hnum %>
      <% if company.hidden? %>
        <span class="label secondary">ждет подтверждения администрацией</span>
      <% end %>
      <% if !current_user.nil? && current_user.admin? %>
        <span class="label warning"><%= company.user %></span>
      <% end %>



</div>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
   <div class="field">
     <%= f.label :category %><br>
   <select name="company[category_id]" id="company_category_id">
  <% Category.walk_tree do |category, level| %>
  <option value="<%= category.id %>" <%='selected' if category.id == @company.category_id%> ><%= '>' * level %> <%= category.name %></option> %>
  <% end %>
  </select>


    </div>

    <div class="field">
      <%= f.label :description %><br>
        <%= quill_editor nil, { name: 'company[description]', value: @company.description }%>
   </div>
   <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
   <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
   <%= f.label :worktime %><br>
   <%= f.text_field :worktime %>
 </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.collection_select :city_id, City.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.collection_select :street_id, Street.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :hnum %><br>
    <%= f.text_field :hnum %>
  </div>
  <% if !current_user.nil? && current_user.admin? then %>
  <div class="field">
    <%= f.label "Hidden?" %> <br />
    <%= f.check_box :hidden %> <br />
</div>
 <% end %>
  <div class="actions">
    <%= f.submit 'Добавить', :class => "button" %>
  </div>
<% end %>

app/views/companies/_table.html.erb
<div class="column row">

<% @companies.each do |company| %>
<div class="card">
  <div class="card-divider">
    <span class="title"><%= link_to company.name, company%></span>
    <% if !current_user.nil? && current_user.admin? %>

      <%= link_to 'Редактировать', edit_company_path(company), :class=>'button warning small' %>
      <%= link_to 'Удалить', company, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'button alert small' %>
    <% end %>
  </div>
  <div class="content">
      Категория: <%= link_to company.category.name, companies_list_path(company.category.id)%>
  </div>
  <div class="action">
      <%= link_to company.city.name, streets_list_path(company.city.id) %>, <%= link_to company.street.name, company.street %>, <%= company.hnum %>
      <% if company.hidden? %>
        <span class="label secondary">ждет подтверждения администрацией</span>
      <% end %>
      <% if !current_user.nil? && current_user.admin? %>
        <span class="label warning"><%= company.user %></span>
      <% end %>



</div>
<% end %>
</div>

app/views/companies/edit.html.erb
<h1>Изменить данные организации</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/list.html.erb
<%
  title 'Категория: ' + @category.name
  keywords [@category.name,'Организации', 'Компании'].reject(&:empty?).join(',')
  %>

   <div id="map">
  <%= map(:center => {
    :latlng => [54.6872, 25.2797],
    :zoom => 12
  },
  :markers => @markers
  ) %>
</div>
<%= render partial: "companies/company", collection: @companies %>

app/views/companies/my.html.erb
<%= render 'companies/table' %>

app/views/companies/new.html.erb
<h1>Добавить организацию:</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<%
  title @company.name
  keywords [@company.name, @company.category.name, @company.street.name, @company.city.name, 'Организации', 'Компании'].reject(&:empty?).join(',')
  %>

<style>
#map { height: 380px; }
</style>

<div class="card">
  <div class="card-divider">
    <h1><%= @company.name %><%= link_to 'Edit', edit_company_path(@company), :class=>'button small warning' if !current_user.nil? && current_user.admin? %></h1>
  </div>
  <div class="card-section">
		<h5><%= link_to @company.city.name, streets_list_path(@company.city.name) %>, <%= link_to @company.street.name, @company.street %>, <%= @company.hnum %> </h5>
		<div class="phone"><%= @company.phone %></div>
		 <div class="card-divider"><div class="website"><%= @company.website %></div></div>
<%= map(:center => {
     :latlng => [@company.lat, @company.lng],
     :zoom => 16
     },
     :markers => [
         {
        :latlng => [@company.lat, @company.lng],
        :popup => @company.name
         }
       ]
     ) %>

		<div class="content description">
			<%= sanitize @company.description %>
		</div>

  </div>
</div>