config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :companies

  resources :entities
  resources :cities
  resources :streets

  get 'cat/:cid' => 'companies#list', as: 'companies_list'
  get ':city/:letter' => 'streets#list', as: 'streets_list', :defaults => { :letter => "A" }
  get 'streetsfix' => 'streets#fix'
  get 'page/index' => 'pages#index'
  get 'signin' => 'pages#signin', as: 'signin'

  get 'my' => 'companies#my', as: 'my'

  get 'page/welcome' => 'pages#welcome'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <div data-closable class="callout alert-callout-border <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
    <%= content_tag :div, msg %>
    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= display_meta_tags site: 'HOM.LT Знаем что где' %>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tag %>
  </head>

  <body>
<div class="top-bar">
  <div class="top-bar-title">
  <%= link_to image_tag("homlt.png", :alt => "HOM.LT", :height => '10'), root_path %>
  </div>
  <div>
    <div class="top-bar-left"><%= render 'cities/list' %></div>
    <div class="top-bar-right">
       <ul class="dropdown menu" data-dropdown-menu>
       <% if current_user %>
                  <li><strong><%= link_to image_tag('person.png', style: 'height:30px'), my_path %></strong>
                  <ul class="menu vertical">
                    <li><%= link_to "Выход", destroy_user_session_path, :method => :delete, :class=>'button small' %></li>
                    </ul>
                    </li>
        <% else %>

         <li><strong><%= link_to image_tag('person.png', style: 'height:30px'), my_path %></strong>
         <ul class="menu vertical">
                  <li>Войти :</li>
                  <li><%= link_to ('<i class="fa fa-facebook fa-5" aria-hidden="true"></i>Facebook').html_safe, user_omniauth_authorize_path(:facebook) %></li>
                  <li><%= link_to ('<i class="fa fa-vk fa-5" aria-hidden="true"></i>Vkontakte').html_safe, user_omniauth_authorize_path(:vkontakte) %></li>
          </ul>
        </li>
        <% end %>

      </ul>



          </div>
  </div>
</div>

<div class="container">
  <div class="small-2 columns">
      <!--Left Block Data-->
      <div class="row">
      <%= link_to '+ Добавить организацию', new_company_path, :class=>"button warning" %>
    </div>
    <div class="row">


      <ul class="vertical menu" data-accordion-menu>
        <% @categories.each do |category| %>
        <li>
          <%= link_to category.name, companies_list_path(category.id) %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="small-10 columns">
    <%= render 'layouts/messages' %>
    <%= yield %>

  </div>
</div>

<div class="row" id='footer'>

</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= Rails.application.secrets.google_code %>', 'auto');
  ga('send', 'pageview');

</script>

  </body>
</html>